### ISSUE TITLE
Allow uploading custom books

### ISSUE THREAD

**Issue by knoellle** [entertrained/entertrained-issues#1]
**Is your feature request related to a problem? Please describe.**
Though there is a decent collection of books available, it would be great if I could use a book that I'm currently reading anyways.

**Describe the solution you'd like**
Allow users to "upload" books. They may be stored in local storage like the user data to avoid legal issues.

**Describe alternatives you've considered**

**Additional context**
Many typing practice programs have a way of supplying custom text. However, none I have seen so far allow tracking and resuming progress throughout a longer text.

**Comment by FaunuX** [comment]
Using epub or something like that could be helpful

**Comment by caderek** [comment]
Thank you for the suggestion - it's the most requested feature, and it's the main thing I'm working on right now (together with user accounts and synchronization between devices). Hard to tell when it will be ready, but it's my priority. I plan to support EPUBs without DRM, and TXT files for starters.

**Comment by caderek** [comment]
I just released the initial version of the custom uploads - you can now upload up to three EPUBs for free, more options coming soon.

The feature is available in version `1.13.0` you may need to refresh the page to see the changes).

Direct link to the feature: https://entertrained.app/books?tab=private

I consider this issue closed for now, if there are any problems or requests, please open a new issue.

Happy typing!

**Comment by why-trv** [comment]
Awesome app, thank you so much @caderek! 
Do you have a timeline for when we're going to be able to add more than 3 books? I don't want to loose my stats by deleting old books to make room for new ones :)
