### ISSUE TITLE
The ability to import EPUB files onto the website.

### ISSUE THREAD

**Issue by Lorino06** [entertrained/entertrained-issues#13]
The current selection of books is really good, but i would be great to have books you own digital copies of be usable on the website, not to mention books in different languages.

I would love the ability to import books onto the website that are downloaded onto your computer.

I'm using the EPUB file type as an example but i'm not too sure if their might be a better way to implement it, they would essentially be digital copies of books that would already be on your computer and could be implemented into the format seen with other novels on the website.

**Comment by wChoros** [comment]
bump. I would also really appreciate this feature. If you would like some help, I'm happy to collaborate :) you can contact me @ twoface1667@gmail.com

**Comment by entertrained** [comment]
The identical issue is already opened as #1 so I will close this one to avoid duplicates.

The feature is already in the works, and I hope to release the initial version at the end of the week.
