### ISSUE TITLE
Words per minute calculation

### ISSUE THREAD

**Issue by frontmesh** [entertrained/entertrained-issues#14]
After using entertained app for a while, to me, its seems that wpm calculation is a bit off.
This is noticeable on smaller paragraphs where wpm most of the time appears to be calculated low..  The smaller the paragraph is the slower the wpm calculation it will be. 

I also use keybr.com app from time to time and my average typing speed there currently is around 70 wpm, while on entertained my average speed is barely 60 wpm and my max speed ever is somewhere around 70. It looks like there is some disparity between wpm calculation between these two apps, but the biggest reason which lead me thinking that something is off with entertained's calculation is that smaller paragraphs length usually result in lower calculated wpm speeds , below 50 wpm, even with just few or no mistakes. 

has anyone noticed something similar?

**Comment by caderek** [comment]
The general formula for calculating WPM is the same on both websites, following the standard definition:



```
WPM = (characters_typed / 5) * (60 / time_in_seconds)
```



For correctly typed text, the WPM should be the same for both apps (I tested it, and it is indeed the case).

Where the apps differ is in how they handle mistakes:

* On **keybr**, the app does not allow you to proceed until you correct your mistake, but it also does not require you to hit `Backspace` to correct the mistake (just hit the correct letter eventually).
* On **Entertrained**, you can proceed freely, and if you want to correct a mistake, you need to use `Backspace`. If you choose to ignore the mistakes, you are penalized - every word that contains an unfixed mistake (underlined) is not counted toward your WPM in that paragraph (similar to how Monkeytype operates).

The reason for this difference is that our approach simulates real-world typing, where you use `Backspace` to correct mistakes. If you ignore mistakes, you would eventually need to go back and fix them, losing more time than if you corrected them immediately.

This should explain the perceived differences and why shorter paragraphs seem slower - if you make a mistake in one word in a short paragraph (and do not fix it), the penalty is a much greater percentage-wise than an unfixed typo in a longer paragraph.

Additionally, the vocabulary on Entertrained is generally richer than on keybr, which can also affect your speed in paragraphs where you don’t make mistakes or fix all mistakes.

I hope this explains the difference you see and why I believe our approach leads to more fruitful typing practice. If you have any questions, let me know.
