### ISSUE TITLE
disable/configure shortcuts (esp. "shift+enter")

### ISSUE THREAD

**Issue by 7UR7L3** [entertrained/entertrained-issues#17]
**Is your feature request related to a problem? Please describe.**
I very often mistype `"` (left_shift+') as shift+enter which deletes my current progress in a paragraph and "marks the paragraph as read" where I seem to have no choice but to re-type that paragraph. Normal enter doesn't have this problem because it simply inserts an underscore.

This is particularly infuriating when it happens on the last paragraph of a chapter and I get immediately redirected away from the passage and it is quite a navigational pain to get back to the last page of the last chapter from the contents to then un-mark it as read to then have another chance at typing it properly.

**Describe the solution you'd like**
Shortcuts settings to enable/disable shortcuts or to configure them to different bindings.

**Describe alternatives you've considered**
ctrl+z? Get good?

**Comment by entertrained** [comment]
You can disable the Shift+Enter behavior in typing mode settings:

https://entertrained.app/settings#typing-mode

In case you have trouble finding it, it's the "Mark as Read" option.

**Comment by entertrained** [comment]
In case you have trouble finding it, it's the "Mark as Read" option.

Best,
Maciej Caderek,
Core Dev and Founder,
Entertrained.app

**Comment by 7UR7L3** [comment]
aha there it is! thank you!
