### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by edarzh** [entertrained/entertrained-issues#2]
**Is your feature request related to a problem? Please describe.**
The selection of fonts doesn't have the one I want unfortunately

**Describe the solution you'd like**
Ability to select locally installed font (like on monkeytype)

**Comment by caderek** [comment]
Hi, I added the feature in `v1.6.0`, it's already live (you may have to refresh the page to see the changes). You can now provide custom font for reading mode, typing mode, and screen keyboard.

I may extend it in the future so you can also choose font-weight and other variants, but for now I consider it closed. Let me know if it works for you.

**Comment by edarzh** [comment]
Thanks! Works great
