### ISSUE TITLE
Mark books as done/unstarted

### ISSUE THREAD

**Issue by allenmhc** [entertrained/entertrained-issues#3]
I couldn't find any UI to do this, but given there's a system of sorts already to track which books you've started typing and which you've finished, having some interface to toggle between the various states would be helpful. For instance, it seems like *Meditations* has a bug where it's flagging the title text as a "chapter" to finish but it can't mark it as finished, so the book is in essence incomplete-able. Other cases, it'd be when you'd start a book, realize it's not a great fit for what you want to practice and want to just un-start it altogether and keep it off of the "in progress" list.

**Comment by caderek** [comment]
Hi, there are two issues here, I will fist address the bug with books progress:

I updated the website so the bug shouldn't reoccur in the future, to fix the existing data:

1. Make a backup of you save data, to do this go to [Settings](https://entertrained.app/settings#manage-data) and export your save file.
2. Press `Ctrl+.` to open app's command line, and type `fix progress`.
3. Wait until the confirmation notification shows up (it may take a while), then reload the page.

If it doesn't work, then you may still get a stale data from the browser cache. To clear the cache on Chrome or some other Chrome-based browsers, open dev tools (that’s `CMD+Option+I` on a Mac, and `CTRL+Shift+I` or `F12` on Windows, Linux, and Chromebooks). With dev tools opened (on the Entertrained website), right-click the Refresh button next to the address bar, and click `Empty Cache and Hard Reload`. Then repeat the steps 2-3.

---

I'm working on the feature to mark books as unread/read.

**Comment by allenmhc** [comment]
The `fix progress` command did the trick! Thanks for the hidden instructions. :)

I'll keep this issue open for what's stated on the title.

**Comment by 4itor** [comment]
The `fix progress` command almost dit it for me, in my case with the tutorial book.
The chapters are now all marked as done (the third one was'nt) but the book is still at 99.9%;

Very nice project, btw. Congrats!

**Comment by caderek** [comment]
@4itor Did you try to clear the cache as I described? If you use a browser other then Chrome and don't know how to do that, let me know and I will write the instructions.

**Comment by 4itor** [comment]
It was as a downloaded PWA app, will try to delete cache as well.

**Comment by 4itor** [comment]
Tried on the browser (checked that data is shared between browser and PWA).

Did: Delete cache and force refresh, did the `fix progress` command again, and an aditional refresh.

All chapters at 100% but book overall still at 99%

![image](https://github.com/user-attachments/assets/1beeea79-7378-4de9-91d1-fb93bf92750e)

**Comment by caderek** [comment]
@4itor Could you please try running `fix progress`  again (without clearing cache this time). There was a bug in this specific book (it's a pity that it was a tutorial of all things 😅). It should now fix the problem (I hope). Sorry for inconvenience, and thank you for patience!

Just make sure you're on version 1.7.7 (it's written at the top on Settings page - you may need to refresh the page)

Oh, and if the fix works, enjoy your final summary of the tutorial:  https://entertrained.app/results/entertrained--first-steps__002

**Comment by 4itor** [comment]
Yay!!! Fixed it!

And the final summary and the fireworks were just cherry on top!

Thank you!

**Comment by caderek** [comment]
Finally got to it - you can now mark the books as read/unread on the book details page (added in v 1.15.0, you may have to refresh the page):

![mark_as_read](https://github.com/user-attachments/assets/c0a9e4d2-b008-44e0-8f9b-96cb7b0223ac)
