### ISSUE TITLE
Ability to change the daily objective. 

### ISSUE THREAD

**Issue by 4itor** [entertrained/entertrained-issues#4]
I would like to have the ability to change the daily objective, graphically on the profile or via some command.

Is it possible?

Thanks in advance.

**Comment by caderek** [comment]
It's possible and thank you for the suggestion. I was thinking about this, but I want to also add some achievements in the future for daily goal streaks etc., so I didn't want to rush this option, and wanted to plan how it would work together. But as there is a need for this I will try to figure something out soon. Maybe keep the fixed daily goal for the achievements to be fair, and add additional personal goal? What do you think? Also, do you find the daily goal to long or to short?

**Comment by 4itor** [comment]
I would love to set a personal daily goal, in my case I just want to type consistently for several minutes a day.

I'm thinking on 5 minutes daily; I usually do it on work breaks, so 15 minutes for me is too much.

About the names: maybe they can be named 'personal goal' and 'daily achievement goal', dunno.

Thanks again for your time and efforts.

If you need some kind betatest on anything just ask, I'd love to help.

**Comment by caderek** [comment]
I thought about it for a while, and decided to make the daily goal customizable from 5 to 30 minutes (in 5 min increments). I think it's a reasonable range, as less than 5 minutes a day I think is to short to develop a good muscle memory, and beyond 30 minutes is to hard to achieve regularly. In addition to that, I decided to count any of these goals towards future achievements - as I don't want to penalize people who are to busy to practice full 15 minutes, but are still practicing regularly.

You can now change it in [Typing Mode Settings](https://entertrained.app/settings#typing-mode) under `Daily Goal` field (the last setting).

Added in v1.8.0 (you may have to refresh the page to see the changes)

Let me know if it works for you, so I can close this issue.

**Comment by 4itor** [comment]
Tried and definitely works for me!!
Thank you!
