### ISSUE TITLE
Unable to Open Console in Firefox

### ISSUE THREAD

**Issue by knoellle** [entertrained/entertrained-issues#5]
I'm facing the same progress issue mentioned in #3, where books or in my case single chapters show 99% completion.
However, the suggested fix does not work for me, since `Ctrl` + `Shift` + `p` opens a private window in Firefox and the app's console does not appear.

I also tried exporting my data, importing it in chromium, running the fix command there and reimporting the data back to Firefox.
However, while this resulted in 100% completion being shown in chromium, Firefox now shows two chapters at 99% where there was only one such chapter previously.

On the other hand, when importing the exact same backup file into a clean session in Firefox, the chapters show correctly as 100%. It seems that the data import does not cleanly restore the progress.

Using Firefox 130.0.1 and Chromium 129.0.6668.70.

**Comment by caderek** [comment]
I added an alternative shortcut to open the app console - it's `Ctrl + .`

> It seems that the data import does not cleanly restore the progress.

Yeah, that's true, in a way. The import function does not clear the cached data like the `fix progress` command does, but I  want to avoid clearing cache every time that this function is executed (as it is not needed most of the time).

Anyway, please retry the `fix progress` command, it should solve the issue (I plan to add these hot fixes to execute in the background without explicit command in the future).

**Comment by knoellle** [comment]
Thank you for the quick response; worked perfectly!
