### ISSUE TITLE
Focused line location

### ISSUE THREAD

**Issue by alonando** [entertrained/entertrained-issues#6]
Great software, and great attention to detail. I'm enjoying practicing typing on a new split keyboard a lot.

Please add a setting to keep the focused line in the middle of the page 'vertically' until the current page is finished. That is, blank space would keep scrolling up under the text until the page is done. This would help to keep the line at a comfortable height at all times.

**Comment by caderek** [comment]
Thank you that is a great suggestion. I added it already, and made it a default setting (it can still be turned off in [Typing Mode Settings](https://entertrained.app/settings#typing-mode)  as a `Keep Centered` option).

Added in v1.8.0 (you may have to refresh the page to see the changes)

Let me know if it works for you, so I can close this issue.

**Comment by alonando** [comment]
That worked great! Thanks for the quick turnaround.
